### ISSUE TITLE
PCANet for 3 input channels

### ISSUE THREAD

**Issue by damhurmuller** [styleNie/PCANet_python#3]
This implementation support for 3 input channels? I got this error when I try:

Traceback (most recent call last):
  File "pcanet_plantas.py", line 67, in <module>
    ftrain,V,BlkIdx = pcanet.PCANet_train(train_x,PCANet,1)
  File "/home/mario/Downloads/PCANet_python-master/PCANet/pcanet.py", line 111, in PCANet_train
    V.append(PCA_FilterBank(OutImg, PCANet.PatchSize[stage], PCANet.NumFilters[stage]))
  File "/home/mario/Downloads/PCANet_python-master/PCANet/pcanet.py", line 77, in PCA_FilterBank
    Rx = Rx + im.dot(im.T)
ValueError: operands could not be broadcast together with shapes (147,147) (49,49) 

I supposed that implementation is set to MNIST dataset from the original paper right? But for cifar10, for example, can it works?

**Comment by arunadevikaruppasamy** [comment]
i am also getting this type of error. have u resolved it,if so kindly help me in this issue.
