### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead:

### ISSUE THREAD

**Issue by arunadevikaruppasamy** [styleNie/PCANet_python#4]
====== PCANet Testing =======

Traceback (most recent call last):
  File "Demo_mnist_basic.py", line 117, in <module>
    pred_label=svm_model.predict(ftest)
  File "C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\linear_model\base.py", line 281, in predict
    scores = self.decision_function(X)
  File "C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\linear_model\base.py", line 257, in decision_function
    X = check_array(X, accept_sparse='csr')
  File "C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\utils\validation.py", line 552, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[41.79591837  0.          0.         ...  0.          0.
  0.        ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by JihaoLee** [comment]
You can modify the code
`pred_label=svm_model.predict(ftest.reshape(1, -1))`
What's your accuracy rate in the implemention? Why my accuracy rate is less than 10%?

**Comment by Jihao-Li** [comment]
@arunadevikaruppasamy 
You can modify the code
`pred_label=svm_model.predict(ftest.reshape(1, -1))`
What's your accuracy rate in the implemention? Why my accuracy rate is less than 10%?
